ALTER TABLE users ADD COLUMN "tokenVersion" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE api_keys ADD COLUMN "keyHash" VARCHAR(200);
ALTER TABLE api_keys ADD COLUMN "keyPrefix" VARCHAR(50);
ALTER TABLE api_keys ADD COLUMN "expiresAt" VARCHAR(100);
